Fix missing brace when WIRE1_SUPPORT not defined
The closing brace was placed inside the preprocessor conditional statement, which caused compilation to fail when WIRE1_SUPPORT was not defined:

E:\arduino\libraries\arduino-as1115\AS1115.cpp: In member function 'byte AS1115::as1115WriteRegister(byte, byte, byte)':

E:\arduino\libraries\arduino-as1115\AS1115.cpp:220:33: error: qualified-id in declaration before '(' token

 byte AS1115::as1115WriteRegister(byte reg, byte val) {